swagger: "2.0"
info:
  title: Account Limits
  x-ibm-name: account-limits
  x-ibm-summary: |
    Latest version from TEST 4-Mar-2021
  version: 1.0.8
  description: This API returns the Account (Credit, Debit, Request) limits  of a
    user (Daily Limit, Monthly Limit, Yearly Limit, Daily Remaining Limit, Monthly
    Remaining Limit, Yearly Remaining Limit)
host: $(catalog.host)
schemes:
- https
basePath: /
produces:
- application/json
consumes:
- application/json
security:
- oauthmerchant:
  - merchant
- oauthconsumer:
  - consumer
- oauth-consumer:
  - consumer
securityDefinitions:
  oauth-consumer:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider-consumer
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider-consumer/oauth2/token
    scopes:
      consumer: ""
  oauthconsumer:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider/oauth2/token
    scopes:
      consumer: ""
  oauthmerchant:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider/oauth2/token
    scopes:
      merchant: Default Scope for Client Auth
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - gatewayscript:
        version: 2.0.0
        title: gatewayscript
        source: context.message.header.set('X-META-DATA','mohabashraf');
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(target-url)$(request.path)
        follow-redirects: false
        timeout: 120
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
    catch: []
  properties:
    target-url:
      value: http://account-management-microservice.m11s:3000
      description: The URL of the target service
      encoded: false
  activity-log:
    success-content: activity
    error-content: header
    enabled: true
  application-authentication:
    certificate: false
  catalogs: {}
  buffering: true
  cors:
    enabled: true
tags:
- externalDocs:
    description: Find out more on box
    url: http://box.ibm
  name: Account Limits
definitions:
  Response:
    type: object
    properties:
      accountLimits:
        type: object
        properties:
          dailySendingLimit:
            type: number
            example: 2000
          dailyReceivingLimit:
            type: number
            example: 1000
          monthlySendingLimit:
            type: number
            example: 30000
          monthlyReceivingLimit:
            type: number
            example: 30000
          yearlySendingLimit:
            type: number
            example: 160000
          yearlyReceivingLimit:
            type: number
            example: 360000
      remainingLimits:
        type: object
        properties:
          dailySendingLimit:
            type: number
            example: 13
          dailyReceivingLimit:
            type: number
            example: 23
          monthlySendingLimit:
            type: number
            example: 1121
          monthlyReceivingLimit:
            type: number
            example: 122
          yearlySendingLimit:
            type: number
            example: 4213
          yearlyReceivingLimit:
            type: number
            example: 1213
  additionalObject:
    type: object
    properties:
      key:
        type: string
        example: abc
      value:
        type: string
        example: def
paths:
  /rest/api/v1/account/limits:
    post:
      tags:
      - Account Limits
      summary: Get Account Limits
      description: ""
      produces:
      - application/json
      parameters:
      - name: X-APP-TYPE
        in: header
        required: true
        description: Describes application or device type.
        type: string
      - name: X-APP-VERSION
        in: header
        required: true
        description: Describes application version 1.0.1.
        type: string
      - name: X-DEVICE-ID
        in: header
        required: true
        description: Describes device ID XDFSD23345435.
        type: string
      - name: X-IP-ADDRESS
        in: header
        required: true
        description: Describes IP Address of the device.
        type: string
      - name: X-CHANNEL
        in: header
        required: true
        description: Describes channel code
        type: string
      - name: X-MSISDN
        in: header
        required: true
        type: string
      - name: X-MPIN
        in: header
        required: true
        type: string
      responses:
        "200":
          description: successful operation
        "401":
          description: Authentication Failed
        "422":
          description: Failed to get account limits.
      consumes: []
