swagger: "2.0"
info:
  title: Contact Integration
  x-ibm-name: contact-integration
  version: 1.0.5
  description: This API is used for syncing contacts.It will take the list of contacts
    and after processing return list of jazzcash users.
host: $(catalog.host)
schemes:
- https
basePath: /
produces:
- application/json
consumes:
- application/json
security:
- oauthconsumer:
  - consumer
- oauthmerchant:
  - merchant
- oauth-consumer:
  - consumer
securityDefinitions:
  oauth-consumer:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider-consumer
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider-consumer/oauth2/token
    scopes:
      consumer: ""
  oauthmerchant:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider/oauth2/token
    scopes:
      merchant: ""
  oauthconsumer:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider/oauth2/token
    scopes:
      consumer: ""
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - gatewayscript:
        version: 2.0.0
        title: gatewayscript
        source: context.message.header.set('X-META-DATA','jazzcash.test.user@gmail.com');
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(target-url)$(request.path)
        follow-redirects: false
        timeout: 120
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://account-management-microservice.m11s:3000
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
  cors:
    enabled: true
definitions:
  contactIntegration_request:
    type: object
    properties:
      contacts:
        type: array
        items:
          type: string
        example:
        - "9232192727201"
        - "9232192727202"
        - "9232192727203"
        - "9232192727204"
  AM-CI-T01_Success:
    type: object
    properties:
      success:
        type: boolean
        example: true
      responseCode:
        type: string
        example: AM-CI-T01
      responseMessage_en:
        type: string
        example: successfully get the jazzcash contacts
      responseMessage_ur:
        type: string
        example: successfully get the jazzcash contacts
      data:
        type: object
        properties:
          msisdn:
            type: string
            example: "9232192727200"
          contacts:
            type: array
            items:
              type: string
            example:
            - contact: "923005066526"
              type: 1
            - contact: "9232192727201"
              type: 2
  422_AM-CI-T02:
    type: object
    properties:
      success:
        type: boolean
        example: false
      responseCode:
        type: string
        example: AM-CI-T02
      responseMessage:
        type: string
        example: Fail to get list of jazzcash users
  contactType_request:
    type: object
    properties:
      contact:
        type: string
        example: "9232192727204"
  AM-CI-T03_Success:
    type: object
    properties:
      success:
        type: boolean
        example: true
      responseCode:
        type: string
        example: AM-CI-T03
      responseMessage_en:
        type: string
        example: This contact is a jazzcash customer
      responseMessage_ur:
        type: string
        example: This contact is a jazzcash customer
      data:
        type: object
        properties:
          msisdn:
            type: string
            example: "9232192727200"
          contact:
            type: string
            example: "9232192727204"
          type:
            type: string
            example: "1"
  422_AM-CI-T04:
    type: object
    properties:
      success:
        type: boolean
        example: false
      responseCode:
        type: string
        example: AM-CI-T04
      responseMessage:
        type: string
        example: This contact is not a jazzcash customer
paths:
  /rest/api/v1/account/contacts:
    post:
      operationId: jazzcashContacts
      description: return list of jazzcash users list
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: header
        name: X-APP-TYPE
        required: true
        type: string
        enum:
        - Andriod
        - IOS
        - Web
        description: Describes application or device type.
      - in: header
        name: X-APP-VERSION
        required: true
        type: string
        description: Describes application version 1.0.1.
      - in: header
        name: X-DEVICE-ID
        required: true
        type: string
        description: Describes device ID XDFSD23345435.
      - in: header
        name: X-IP-ADDRESS
        required: true
        type: string
        description: Describes IP Address of the device.
      - in: header
        name: X-CHANNEL
        required: true
        type: string
        enum:
        - Third Party
        - Mobile APP
        - Backend Portal
        description: Describes channel code
      - in: header
        name: X-MSISDN
        required: true
        type: string
      - name: body
        in: body
        schema:
          $ref: '#/definitions/contactIntegration_request'
          description: The request body for the operation
      responses:
        "200":
          description: 'code: 200  (type=1 mean consumer ant 2 mean merchant)'
          schema:
            $ref: '#/definitions/AM-CI-T01_Success'
        "422":
          description: 'code: 422'
          schema:
            $ref: '#/definitions/422_AM-CI-T02'
  /rest/api/v1/account/contact:
    post:
      operationId: contactType
      description: return contact is either consumer or merchant
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: header
        name: X-APP-TYPE
        required: true
        type: string
        enum:
        - Andriod
        - IOS
        - Web
        description: Describes application or device type.
      - in: header
        name: X-APP-VERSION
        required: true
        type: string
        description: Describes application version 1.0.1.
      - in: header
        name: X-DEVICE-ID
        required: true
        type: string
        description: Describes device ID XDFSD23345435.
      - in: header
        name: X-IP-ADDRESS
        required: true
        type: string
        description: Describes IP Address of the device.
      - in: header
        name: X-CHANNEL
        required: true
        type: string
        enum:
        - Third Party
        - Mobile APP
        - Backend Portal
        description: Describes channel code
      - in: header
        name: X-MSISDN
        required: true
        type: string
      - name: body
        in: body
        schema:
          $ref: '#/definitions/contactType_request'
          description: The request body for the operation
      responses:
        "200":
          description: 'code: 200  (type=1 mean consumer ant 2 mean merchant)'
          schema:
            $ref: '#/definitions/AM-CI-T03_Success'
        "422":
          description: 'code: 422'
          schema:
            $ref: '#/definitions/422_AM-CI-T04'
  /rest/api/v1/consumer/contacts:
    post:
      operationId: jazzcashContacts_v0
      description: return list of jazzcash users list(it is same as rest/api/v1/account/contacts)
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: header
        name: X-APP-TYPE
        required: true
        type: string
        enum:
        - Andriod
        - IOS
        - Web
        description: Describes application or device type.
      - in: header
        name: X-APP-VERSION
        required: true
        type: string
        description: Describes application version 1.0.1.
      - in: header
        name: X-DEVICE-ID
        required: true
        type: string
        description: Describes device ID XDFSD23345435.
      - in: header
        name: X-IP-ADDRESS
        required: true
        type: string
        description: Describes IP Address of the device.
      - in: header
        name: X-CHANNEL
        required: true
        type: string
        enum:
        - Third Party
        - Mobile APP
        - Backend Portal
        description: Describes channel code
      - in: header
        name: X-MSISDN
        required: true
        type: string
      - name: body
        in: body
        schema:
          $ref: '#/definitions/contactIntegration_request'
          description: The request body for the operation
      responses:
        "200":
          description: 'code: 200  (type=1 mean consumer ant 2 mean merchant)'
          schema:
            $ref: '#/definitions/AM-CI-T01_Success'
        "422":
          description: 'code: 422'
          schema:
            $ref: '#/definitions/422_AM-CI-T02'
