swagger: "2.0"
info:
  title: Daraz Wallet Top-up Initiate
  x-ibm-name: daraz-wallet-top-up-initiate
  version: 1.0.5
  description: |-
    This API will initiate Daraz wallet top-up
    Disabling CORS
host: $(catalog.host)
schemes:
- https
basePath: /
produces:
- application/json
consumes:
- application/json
security:
- oauthconsumer:
  - consumer
- oauth-consumer:
  - consumer
securityDefinitions:
  oauth-consumer:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider-consumer
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider-consumer/oauth2/token
    scopes:
      consumer: ""
  oauthconsumer:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider/oauth2/token
    scopes:
      consumer: ""
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - gatewayscript:
        version: 2.0.0
        title: gatewayscript
        source: context.message.header.set('x-user-metadata',context.get('oauth.verified_access_token.misc_info'));
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(target-url)$(request.path)
        follow-redirects: false
        timeout: 120
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://walletmanagement-microservice.m11s:3000
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
  catalogs: {}
  cors:
    enabled: true
definitions:
  initDarazTopup:
    type: object
    properties:
      amount:
        type: string
        example: ""
      remarks:
        type: string
        example: ""
      additionaldetails:
        type: array
        items:
          type: object
          properties:
            key1:
              type: string
              example: value
  200_completed:
    type: object
    properties:
      success:
        type: boolean
        example: true
      responseCode:
        type: string
        example: WM-DW-T01
      message_en:
        type: string
        example: Daraz wallet topup initiation done successfully
      message_ur:
        type: string
        example: ""
      data:
        $ref: '#/definitions/initDarazTopupResponse'
  initDarazTopupResponse:
    type: object
    properties:
      originalConversationID:
        type: string
        example: S_X2013012921001
      conversationID:
        type: string
        example: AG_20130129T102103
      transactionID:
        type: string
        example: XD2013012923789234
      targetMSISDN:
        type: string
        example: "9213415678906"
      balance:
        type: string
        example: "1000.1"
      amount:
        type: string
        example: "867.00"
      commission:
        type: string
        example: "20.00"
      fed:
        type: string
        example: "0.5"
      wht:
        type: string
        example: "0.3"
      transEndDate:
        type: string
        example: 2004-01-05T00:00:00.000Z
      transEndTime:
        type: string
        example: "03:33:12.943"
      fee:
        type: string
        example: "0.7"
      maname:
        type: string
        example: ""
      failedReason:
        type: string
        example: ""
      notifyMSISDN:
        type: string
        example: ""
  422_DW02:
    type: object
    properties:
      success:
        type: boolean
        example: false
      responseCode:
        type: string
        example: WM-DW-T02
      message_en:
        type: string
        example: Fail to initiate Daraz wallet top-up
      message_ur:
        type: string
        example: ""
      data:
        type: object
paths:
  /rest/api/v1/wallet/daraz/init:
    post:
      operationId: initDarazTopup
      description: init Daraz Topup
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: header
        name: X-IP-ADDRESS
        required: true
        type: string
        description: Describes IP Address of the device.
      - in: header
        name: X-APP-VERSION
        required: true
        type: string
        description: Describes application version 1.0.1.
      - in: header
        name: X-DEVICE-ID
        required: true
        type: string
        description: Describes device ID XDFSD23345435.
      - in: header
        name: X-DEVICE-TYPE
        required: true
        type: string
        enum:
        - Andriod
        - IOS
        - Web
        description: Describes application or device type.
      - in: header
        name: X-CHANNEL
        required: true
        type: string
        enum:
        - Third Party
        - Mobile APP
        - Backend Portal
        description: Describes channel code
      - in: header
        name: X-MSISDN
        required: true
        type: string
      - name: body
        in: body
        schema:
          $ref: '#/definitions/initDarazTopup'
        description: The request body for the operation
        required: true
      responses:
        "200":
          description: 'code: 200'
          schema:
            $ref: '#/definitions/200_completed'
        "422":
          description: This is a template for business errors should be returned by
            this API
          schema:
            $ref: '#/definitions/422_DW02'
