swagger: "2.0"
info:
  title: Display QR
  x-ibm-name: display-qr
  version: 1.0.4
  description: This API returns QRImage and QRPayload
host: $(catalog.host)
schemes:
- https
basePath: /
produces:
- application/json
consumes:
- application/json
security:
- oauthuser:
  - user
- oauthmerchant:
  - merchant
- oauthconsumer:
  - consumer
- oauth-consumer:
  - consumer
securityDefinitions:
  oauth-consumer:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider-consumer
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider-consumer/oauth2/token
    scopes:
      consumer: ""
  oauthmerchant:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider/oauth2/token
    scopes:
      merchant: ""
  oauthconsumer:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider/oauth2/token
    scopes:
      consumer: ""
  oauthuser:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: oauth-provider
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider/oauth2/token
    scopes:
      user: ""
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: false
  assembly:
    execute:
    - gatewayscript:
        version: 2.0.0
        title: gatewayscript
        source: context.message.header.set('x-user-metadata',context.get('oauth.verified_access_token.misc_info'));
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(target-url)$(request.path)
        follow-redirects: false
        timeout: 120
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://account-management-microservice.m11s:3000
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
  catalogs: {}
tags:
- externalDocs:
    description: Find out more on box
    url: http://box.ibm
  name: Display QR
definitions:
  Response:
    type: object
    properties:
      tillNumber:
        type: string
        example: "00001111"
      merchantMSISDN:
        type: string
        example: 03xxxxxx
      brandName:
        type: string
        example: Khadi
      qrImageSimple:
        type: string
        example: base64Image
      qrImage:
        type: string
        example: Test
  additionalObject:
    type: object
    properties:
      key:
        type: string
        example: abc
      value:
        type: string
        example: def
paths:
  /rest/api/v1/account/qrcode/display/:
    get:
      tags:
      - Display QR Code
      summary: Display QR Code
      description: ""
      produces:
      - application/json
      parameters:
      - name: X-APP-TYPE
        in: header
        required: true
        description: Describes application or device type.
        type: string
      - name: X-APP-VERSION
        in: header
        required: true
        description: Describes application version 1.0.1.
        type: string
      - name: X-DEVICE-ID
        in: header
        required: true
        description: Describes device ID XDFSD23345435.
        type: string
      - name: X-IP-ADDRESS
        in: header
        required: true
        description: Describes IP Address of the device.
        type: string
      - name: X-CHANNEL
        in: header
        required: true
        description: Describes channel code
        type: string
      - name: X-MSISDN
        in: header
        required: true
        type: string
      responses:
        "200":
          description: successful operation
        "401":
          description: Authentication Failed
        "422":
          description: Failed to get QR Image
      consumes: []
