swagger: "2.0"
info:
  title: Donations
  x-ibm-name: donations
  version: 1.0.5
  description: |-
    Donations confirm API to confirm already initiated transactions for any type of Donations
    Disabling CORS
host: $(catalog.host)
schemes:
- https
basePath: /
produces:
- application/json
consumes:
- application/json
security:
- oauthmerchant:
  - merchant
- oauthconsumer:
  - consumer
- oauthuser:
  - user
- oauth-consumer:
  - consumer
securityDefinitions:
  oauth-consumer:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider-consumer
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider-consumer/oauth2/token
    scopes:
      consumer: ""
  oauthconsumer:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider/oauth2/token
    scopes:
      consumer: ""
  oauthmerchant:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider/oauth2/token
    scopes:
      merchant: ""
  oauthuser:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: oauth-provider
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider/oauth2/token
    scopes:
      user: ""
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - gatewayscript:
        version: 2.0.0
        title: gatewayscript
        source: context.message.header.set('x-user-metadata',context.get('oauth.verified_access_token.misc_info'));
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(target-url)$(request.path)
        follow-redirects: false
        timeout: 120
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://payment-and-transaction-microservice.m11s:3000
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
  catalogs: {}
  cors:
    enabled: true
definitions:
  request:
    type: object
    properties:
      transactionID:
        type: string
        example: XD2013012923789234
      transactionType:
        type: string
        example: C2C/BA/CNIC
      remarks:
        type: string
        example: hakjfdsa dajh
      additionalDetails:
        type: object
        properties:
          key:
            type: string
            example: abc
          value:
            type: string
            example: def
  response:
    type: object
    properties:
      originatorConversationID:
        type: string
        example: 247bad68da0e4edaa0ba7eb4ddf3a9cf
      conversationID:
        type: string
        example: AG_20200730_000049564a4e7f3cfc86
      transactionID:
        type: string
        example: 10710713156
      transEndDate:
        type: string
        example: "20200730"
      transEndTime:
        type: string
        example: "150802"
      transactionDetails:
        type: object
        properties:
          amount:
            type: number
            format: double
            example: "10.00"
          channelCode:
            type: string
            example: "1020"
          deduction:
            type: number
            format: double
            example: "10.00"
          commission:
            type: number
            format: double
            example: "0.00"
          receiverMSISDN:
            type: string
            example: "923345494749"
          balance:
            type: number
            example: 0
          wht:
            type: number
            example: 0
          fee:
            type: number
            example: 0
  additionalObject:
    type: object
    properties:
      key:
        type: string
        example: abc
      value:
        type: string
        example: def
paths:
  /rest/api/v1/donations/confirm:
    post:
      operationId: postSync
      tags:
      - ConfirmTransaction
      produces:
      - application/json
      parameters:
      - name: X-APP-TYPE
        in: header
        required: true
        description: Describes application or device type.
        type: string
      - name: X-APP-VERSION
        in: header
        required: true
        description: Describes application version 1.0.1.
        type: string
      - name: X-DEVICE-ID
        in: header
        required: true
        description: Describes device ID XDFSD23345435.
        type: string
      - name: X-IP-ADDRESS
        in: header
        required: true
        description: Describes IP Address of the device.
        type: string
      - name: X-CHANNEL
        in: header
        required: true
        description: Describes channel code
        type: string
      - name: X-MSISDN
        in: header
        required: true
        type: string
      - name: X-MPIN
        in: header
        required: true
        type: string
      - name: body
        in: body
        required: false
        schema:
          $ref: '#/definitions/request'
      responses:
        "200":
          description: The operation was successful.
        "401":
          description: Unable to connect to the Enterprise Service Bus
        "402":
          description: The Request timed out
        "422":
          description: Failed to submit the transaction due to missing mandatory parameters.
        "501":
          description: Unexpected Internal server error
      consumes:
      - application/json
