swagger: "2.0"
info:
  title: Get MSISDN Status
  x-ibm-name: get-msisdn-status
  version: 1.0.5
  description: Endpoint for inquiring if the customer is allowed to place order against
    provided MSISDN. Only submit order if returned code is 100.
host: $(catalog.host)
schemes:
- https
basePath: /
produces:
- application/json
consumes:
- application/json
security:
- oauthmerchant:
  - merchant
- oauthconsumer:
  - consumer
- oauthuser:
  - user
- oauth-consumer:
  - consumer
securityDefinitions:
  oauth-consumer:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider-consumer
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider-consumer/oauth2/token
    scopes:
      consumer: ""
  oauthuser:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: oauth-provider
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider/oauth2/token
    scopes:
      user: Default Scope
  oauthmerchant:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider/oauth2/token
    scopes:
      merchant: ""
  oauthconsumer:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider/oauth2/token
    scopes:
      consumer: ""
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - gatewayscript:
        version: 2.0.0
        title: gatewayscript
        source: context.message.header.set('x-user-metadata',context.get('oauth.verified_access_token.misc_info'));
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(target-url)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
          values: []
        header-control:
          type: blacklist
          values: []
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://secure-card-management-microservice.m11s:3000
      description: The URL of the target service
      encoded: false
  catalogs: {}
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  cors:
    enabled: true
tags:
- externalDocs:
    description: Find out more on box
    url: http://box.ibm
  name: MSISDN Status
  description: Get MSISDN Status
definitions:
  Response:
    type: object
    properties:
      trackingData:
        type: object
        properties:
          orderNo:
            type: string
            example: XXXXX
          orderStatus:
            type: string
            example: XXXXX
          reason:
            type: string
            example: XXXXX
  additionalObject:
    type: object
    properties:
      key:
        type: string
        example: abc
      value:
        type: string
        example: def
paths:
  /rest/api/v1/mastercard/physical/eligibility/check:
    get:
      tags:
      - MSISDN Status
      summary: Get MSISDN Status
      description: ""
      produces:
      - application/json
      parameters:
      - name: X-APP-TYPE
        in: header
        required: true
        description: Describes application or device type.
        type: string
      - name: X-APP-VERSION
        in: header
        required: true
        description: Describes application version 1.0.1.
        type: string
      - name: X-DEVICE-ID
        in: header
        required: true
        description: Describes device ID XDFSD23345435.
        type: string
      - name: X-IP-ADDRESS
        in: header
        required: true
        description: Describes IP Address of the device.
        type: string
      - name: X-CHANNEL
        in: header
        required: true
        description: Describes channel code
        type: string
      - name: X-MSISDN
        in: header
        required: true
        type: string
      responses:
        "200":
          description: successful operation
        "400":
          description: Bad Request on VDC
        "401":
          description: Authentication Failure on VDC
        "406":
          description: Cutomer NOT Allowed to Order Card
        "422":
          description: Invalid Request
      consumes: []
