swagger: "2.0"
info:
  title: insurance
  x-ibm-name: insurance
  version: 1.0.9
  description: APIs to subscribe for Insurance
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
host: $(catalog.host)
schemes:
- https
basePath: /
produces:
- application/json
consumes:
- application/json
security:
- oauthmerchant:
  - merchant
- oauthconsumer:
  - consumer
- oauthuser:
  - user
- oauth-consumer:
  - consumer
securityDefinitions:
  oauth-consumer:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider-consumer
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider-consumer/oauth2/token
    scopes:
      consumer: ""
  oauthuser:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: oauth-provider
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider/oauth2/token
    scopes:
      user: ""
  oauthconsumer:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider/oauth2/token
    scopes:
      consumer: ""
  oauthmerchant:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider/oauth2/token
    scopes:
      merchant: ""
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - gatewayscript:
        version: 2.0.0
        title: gatewayscript
        source: context.message.header.set('x-user-metadata',context.get('oauth.verified_access_token.misc_info'));
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(target-url)$(request.path)
        follow-redirects: false
        timeout: 120
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://insurance-microservice.m11s:3000
      description: The URL of the target service
      encoded: false
  catalogs: {}
  application-authentication:
    certificate: false
  activity-log:
    success-content: payload
    error-content: payload
    enabled: true
  buffering: true
  cors:
    enabled: false
parameters:
  acceptLanguage:
    name: Accept-Language
    description: Describe which language you prefer to get back the response in ,
      current possible values are "en" or "ur" for English and Urdu
    in: header
    type: string
  appType:
    name: X-APP-TYPE
    description: Describes application or device type.
    in: header
    required: true
    type: string
    enum:
    - Andriod
    - IOS
    - Web
  appVersion:
    name: X-APP-VERSION
    description: Describes application version 1.0.1.
    in: header
    required: true
    type: string
  deviceID:
    name: X-DEVICE-ID
    description: Describes device ID XDFSD23345435.
    in: header
    required: true
    type: string
  ipAddress:
    name: X-IP-ADDRESS
    description: Describes IP Address of the device.
    in: header
    required: true
    type: string
  channel:
    name: X-CHANNEL
    description: Describes channel code
    in: header
    required: true
    type: string
    enum:
    - Third Party
    - Mobile APP
    - Backend Portal
  ibmClientID:
    name: X-IBM-CLIENT-ID
    description: Client credentials required for API Connect
    in: header
    required: true
    type: string
  msisdn:
    name: X-MSISDN
    description: Client credentials required for API Connect
    in: header
    required: true
    type: string
definitions:
  request:
    type: object
    properties:
      planID:
        type: number
        example: 56
      pulse:
        type: string
        example: OneTime
      cost:
        type: number
        example: 399
    required:
    - planID
    - cost
  cancellationRequest:
    type: object
    properties:
      planID:
        type: number
        example: 56
      subscriptionID:
        type: number
        example: 456
    required:
    - planID
    - subscriptionID
paths:
  /rest/api/v1/insurance/submitclaim:
    post:
      tags:
      - claim
      responses:
        "200":
          description: Creates a claim with ID for user
          examples:
            application/json:
              success: true
              responseCode: INS-SC-T02
              responseMessage_en: Successfully Submited Claim
              responseMessage_ur: ""
              data:
              - messageId: 23ee0c23-280f-4d82-967d-4dfe482447ac
                claimNumer: CL-JCSS-00000149
        "422":
          description: Error Createing a claim with ID for user
          examples:
            application/json:
              success: false
              responseCode: INS-SC-T04
              responseMessage_en: Unable to Submit Claim
              responseMessage_ur: ""
              data: []
      parameters:
      - name: body
        in: body
        schema:
          type: object
          properties:
            planId:
              type: string
              example: "658"
            planName:
              type: string
              example: Sehat Sahulat
            pulse:
              type: string
              example: Weekly
          required:
          - pulse
      summary: Obtains a customer plans
    parameters:
    - name: Accept-Language
      description: Describe which language you prefer to get back the response in
        , current possible values are "en" or "ur" for English and Urdu
      in: header
      type: string
    - name: X-APP-TYPE
      description: Describes application or device type.
      in: header
      required: true
      type: string
      enum:
      - Andriod
      - IOS
      - Web
    - name: X-APP-VERSION
      description: Describes application version 1.0.1.
      in: header
      required: true
      type: string
    - name: X-DEVICE-ID
      description: Describes device ID XDFSD23345435.
      in: header
      required: true
      type: string
    - name: X-IP-ADDRESS
      description: Describes IP Address of the device.
      in: header
      required: true
      type: string
    - name: X-CHANNEL
      description: Describes channel code
      in: header
      required: true
      type: string
      enum:
      - Third Party
      - Mobile APP
      - Backend Portal
    - name: X-IBM-CLIENT-ID
      description: Client credentials required for API Connect
      in: header
      required: true
      type: string
    - name: X-MSISDN
      description: Client credentials required for API Connect
      in: header
      required: true
      type: string
  /rest/api/v1/insurance/addclaimdoc:
    post:
      tags:
      - claim
      responses:
        "200":
          description: Creates a claim with ID for user
          examples:
            application/json:
              success: true
              responseCode: INS-SC-T03
              responseMessage_en: Succesfully Added Doc to Claim
              responseMessage_ur: ""
              data:
              - messageId: 23ee0c23-280f-4d82-967d-4dfe482447ac
                fileName: My File.jpg
        "422":
          description: Error Createing a claim with ID for user
          examples:
            application/json:
              success: false
              responseCode: INS-SC-T05
              responseMessage_en: Unable to Add Doc to Claim
              responseMessage_ur: ""
              data: []
      parameters:
      - name: body
        in: body
        schema:
          type: object
          properties:
            claimNo:
              type: string
              example: CL-JCSS-00000147
            docType:
              type: string
              example: Identity Document
            docBase64:
              type: string
              example: /9j/4AAQSkZJRgABAQEAYABgAA
          required:
          - claimNo
          - docType
          - docBase64
      summary: Obtains a customer plans
    parameters:
    - name: Accept-Language
      description: Describe which language you prefer to get back the response in
        , current possible values are "en" or "ur" for English and Urdu
      in: header
      type: string
    - name: X-APP-TYPE
      description: Describes application or device type.
      in: header
      required: true
      type: string
      enum:
      - Andriod
      - IOS
      - Web
    - name: X-APP-VERSION
      description: Describes application version 1.0.1.
      in: header
      required: true
      type: string
    - name: X-DEVICE-ID
      description: Describes device ID XDFSD23345435.
      in: header
      required: true
      type: string
    - name: X-IP-ADDRESS
      description: Describes IP Address of the device.
      in: header
      required: true
      type: string
    - name: X-CHANNEL
      description: Describes channel code
      in: header
      required: true
      type: string
      enum:
      - Third Party
      - Mobile APP
      - Backend Portal
    - name: X-IBM-CLIENT-ID
      description: Client credentials required for API Connect
      in: header
      required: true
      type: string
    - name: X-MSISDN
      description: Client credentials required for API Connect
      in: header
      required: true
      type: string
  /rest/api/v1/insurance/claims:
    get:
      tags:
      - claim
      responses:
        "200":
          description: Creates a claim with ID for user
          examples:
            application/json:
              success: true
              responseCode: INS-SC-T06
              responseMessage_en: Succesfully Fetched All Claims
              responseMessage_ur: ""
              data:
              - claimId: adab-234-234
                status: submitted
                submitDate: 2020-02-02T00:00:00.000Z
                docs: []
              - claimId: adab-234-234
                status: submitted
                submitDate: 2020-02-02T00:00:00.000Z
                docs: []
        "422":
          description: Error Createing a claim with ID for user
          examples:
            application/json:
              success: false
              responseCode: INS-SC-T07
              responseMessage_en: Unable Fetch Claim Details
              responseMessage_ur: ""
              data: []
      summary: Retrieves Customer Claims
    parameters:
    - name: Accept-Language
      description: Describe which language you prefer to get back the response in
        , current possible values are "en" or "ur" for English and Urdu
      in: header
      type: string
    - name: X-APP-TYPE
      description: Describes application or device type.
      in: header
      required: true
      type: string
      enum:
      - Andriod
      - IOS
      - Web
    - name: X-APP-VERSION
      description: Describes application version 1.0.1.
      in: header
      required: true
      type: string
    - name: X-DEVICE-ID
      description: Describes device ID XDFSD23345435.
      in: header
      required: true
      type: string
    - name: X-IP-ADDRESS
      description: Describes IP Address of the device.
      in: header
      required: true
      type: string
    - name: X-CHANNEL
      description: Describes channel code
      in: header
      required: true
      type: string
      enum:
      - Third Party
      - Mobile APP
      - Backend Portal
    - name: X-IBM-CLIENT-ID
      description: Client credentials required for API Connect
      in: header
      required: true
      type: string
    - name: X-MSISDN
      description: Client credentials required for API Connect
      in: header
      required: true
      type: string
  /rest/api/v1/insurance/subscriptions:
    post:
      tags:
      - subscribe
      parameters:
      - name: body
        in: body
        required: false
        schema:
          $ref: '#/definitions/request'
      - name: X-MPIN
        in: header
        required: true
        description: Doubly Encrypted MPIN
        type: string
      responses:
        "201":
          description: Successful
        "400":
          description: Not eligible to subscribe
        "500":
          description: System error
      summary: Used to subscribe for Insurance
      security:
      - oauthmerchant:
        - merchant
      - oauthconsumer:
        - consumer
      consumes: []
      produces: []
    put:
      tags:
      - cancel
      parameters:
      - name: body
        in: body
        required: false
        schema:
          $ref: '#/definitions/cancellationRequest'
      responses:
        "200":
          description: Successful
        "422":
          description: Request could not be processed as its invalid
        "500":
          description: System error
      summary: Used to Cancel Insurance
      produces: []
      security:
      - oauthmerchant:
        - merchant
      - oauthconsumer:
        - consumer
      consumes: []
    parameters:
    - name: Accept-Language
      in: header
      required: false
      description: Describe which language you prefer to get back the response in
        , current possible values are "en" or "ur" for English and Urdu
      type: string
    - name: X-APP-TYPE
      in: header
      required: true
      description: Describes application or device type.
      type: string
    - name: X-APP-VERSION
      in: header
      required: true
      description: Describes application version 1.0.1.
      type: string
    - name: X-DEVICE-ID
      in: header
      required: true
      description: Describes device ID XDFSD23345435.
      type: string
    - name: X-IP-ADDRESS
      in: header
      required: true
      description: Describes IP Address of the device.
      type: string
    - name: X-CHANNEL
      in: header
      required: true
      description: Describes channel code
      type: string
    - name: X-MSISDN
      in: header
      required: true
      description: Client credentials required for API Connect
      type: string
    - name: X-IBM-CLIENT-ID
      description: Client credentials required for API Connect
      in: header
      required: true
      type: string
  /rest/api/v1/insurance/plans:
    get:
      tags:
      - subscribe
      parameters:
      - name: type
        description: 'Could be either ''health'' or ''life'' for now '
        in: query
        required: false
        type: string
      responses:
        "200":
          description: "Provides the insurance plans. \nPossible values of \"pulse\"
            could be Annual,Weekly, Monthly , Daily or OneTime"
          examples:
            application/json:
              plans:
              - planID: 99
                name: Health annual
                duration: 10
                premium: 30
                pulseList:
                - OneTime
                description: 'Features: <p> Daily hospital cash benefit Rs. 1,000
                  <p>  Daily ICU confinement benefit Rs. 2,000 <p> Accidental medical
                  expense (Annual) up to Rs. 30,000 '
                termsAndConditions: Lorem Ipsum.....
      summary: Gets available insurance plans
    parameters:
    - name: Accept-Language
      in: header
      required: false
      description: Describe which language you prefer to get back the response in
        , current possible values are "en" or "ur" for English and Urdu
      type: string
    - name: X-APP-TYPE
      in: header
      required: true
      description: Describes application or device type.
      type: string
    - name: X-APP-VERSION
      in: header
      required: true
      description: Describes application version 1.0.1.
      type: string
    - name: X-DEVICE-ID
      in: header
      required: true
      description: Describes device ID XDFSD23345435.
      type: string
    - name: X-IP-ADDRESS
      in: header
      required: true
      description: Describes IP Address of the device.
      type: string
    - name: X-CHANNEL
      in: header
      required: true
      description: Describes channel code
      type: string
    - name: X-MSISDN
      in: header
      required: false
      description: Client credentials required for API Connect
      type: string
    - name: X-IBM-CLIENT-ID
      in: header
      required: false
      description: Client credentials required for API Connect
      type: string
  /rest/api/v1/insurance/myplans:
    get:
      tags:
      - cancel
      responses:
        "200":
          description: Provides the subscribed insurance plans
          examples:
            application/json:
              success: true
              responseCode: INS-SUB-02
              responseMessage_en: ""
              responseMessage_ur: ""
              data:
              - planID: 56
                subscriptionID: 235
                planName: Family Tahafuz
                planDescription: Lorem Ipsum...
                termsAndConditions: Lorem Ipsum.....
                startDate: 01-01-2020
                durationInDays: 365
                cost: 5000
              - planID: 65
                subscriptionID: 240
                planName: Family Tahafuz Premium
                planDescription: Lorem Ipsum...
                termsAndConditions: Lorem Ipsum.....
                startDate: 01-01-2020
                durationInDays: 365
                cost: 5500
      summary: Obtains a customer plans
    parameters:
    - name: Accept-Language
      in: header
      required: false
      description: Describe which language you prefer to get back the response in
        , current possible values are "en" or "ur" for English and Urdu
      type: string
    - name: X-APP-TYPE
      in: header
      required: true
      description: Describes application or device type.
      type: string
    - name: X-APP-VERSION
      in: header
      required: true
      description: Describes application version 1.0.1.
      type: string
    - name: X-DEVICE-ID
      in: header
      required: true
      description: Describes device ID XDFSD23345435.
      type: string
    - name: X-IP-ADDRESS
      in: header
      required: true
      description: Describes IP Address of the device.
      type: string
    - name: X-CHANNEL
      in: header
      required: true
      description: Describes channel code
      type: string
    - name: X-MSISDN
      in: header
      required: true
      description: Client credentials required for API Connect
      type: string
    - name: X-IBM-CLIENT-ID
      description: Client credentials required for API Connect
      in: header
      required: true
      type: string
