swagger: "2.0"
info:
  title: Jazz Mobile Load Confirmation
  x-ibm-name: jazz-mobile-load-confirmation
  x-ibm-summary: 30th March - Merchant Phase-2 Deployment
  version: 1.0.7
  description: This API will confirm jazz mobile load transaction
host: $(catalog.host)
schemes:
- https
basePath: /
produces:
- application/json
consumes:
- application/json
security:
- oauthmerchant:
  - merchant
- oauthconsumer:
  - consumer
- oauth-consumer:
  - consumer
securityDefinitions:
  oauth-consumer:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider-consumer
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider-consumer/oauth2/token
    scopes:
      consumer: ""
  oauthconsumer:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider/oauth2/token
    scopes:
      consumer: ""
  oauthmerchant:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider/oauth2/token
    scopes:
      merchant: ""
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - gatewayscript:
        version: 2.0.0
        title: gatewayscript
        source: context.message.header.set('x-user-metadata',context.get('oauth.verified_access_token.misc_info'));
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(target-url)$(request.path)
        follow-redirects: false
        timeout: 120
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://gsmservicesmanagement-microservice.m11s:3000
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
  catalogs: {}
  cors:
    enabled: true
definitions:
  confirmJazzLoad_request:
    type: object
    properties:
      transactionId:
        type: string
        example: ""
      usecase:
        type: string
        example: ""
      targetMSISDN:
        type: string
        example: ""
      targetName:
        type: string
        example: ""
      amount:
        type: string
        example: ""
      additionaldetails:
        type: array
        items:
          type: object
          properties:
            key1:
              type: string
              example: value
  200_completed:
    type: object
    properties:
      success:
        type: boolean
        example: true
      responseCode:
        type: string
        example: GSM-MB-T84
      message_en:
        type: string
        example: Jazz Mobile Load Transaction Confirmation Done Successfully
      message_ur:
        type: string
        example: ""
      data:
        $ref: '#/definitions/jazzConfirmLoadResponse'
  jazzConfirmLoadResponse:
    type: object
    properties:
      originalConversationID:
        type: string
        example: S_X2013012921001
      conversationID:
        type: string
        example: AG_20130129T102103
      transactionID:
        type: string
        example: XD2013012923789234
      targetMSISDN:
        type: string
        example: "9213415678906"
      balance:
        type: string
        example: "1000.1"
      amount:
        type: string
        example: "867.00"
      commission:
        type: string
        example: "20.00"
      fed:
        type: string
        example: "0.5"
      wht:
        type: string
        example: "0.3"
      transEndDate:
        type: string
        example: 2004-01-05T00:00:00.000Z
      transEndTime:
        type: string
        example: "03:33:12.943"
      fee:
        type: string
        example: "0.7"
      maname:
        type: string
        example: ""
      failedReason:
        type: string
        example: ""
      notifyMSISDN:
        type: string
        example: ""
  422_MB85:
    type: object
    properties:
      success:
        type: boolean
        example: false
      responseCode:
        type: string
        example: GSM-MB-T85
      message_en:
        type: string
        example: Fail To Confirm Jazz Mobile Load Transaction
      message_ur:
        type: string
        example: ""
      data:
        type: object
paths:
  /rest/api/v1/gsm/load/jazz/confirm:
    post:
      operationId: confirmJazzLoad
      description: confirm Jazz Load
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: X-IP-ADDRESS
        in: header
        required: true
        description: Describes IP Address of the device.
        type: string
      - name: X-APP-VERSION
        in: header
        required: true
        description: Describes application version 1.0.1.
        type: string
      - name: X-DEVICE-ID
        in: header
        required: true
        description: Describes device ID XDFSD23345435.
        type: string
      - name: X-DEVICE-TYPE
        in: header
        required: true
        description: Describes application or device type.
        type: string
      - name: X-CHANNEL
        in: header
        required: true
        description: Describes channel code
        type: string
      - name: X-MSISDN
        in: header
        required: true
        type: string
      - name: X-MPIN
        in: header
        required: true
        type: string
      - name: body
        in: body
        required: true
        description: The request body for the operation
        schema:
          $ref: '#/definitions/confirmJazzLoad_request'
      responses:
        "200":
          description: 'code: 200'
          schema:
            $ref: '#/definitions/200_completed'
        "422":
          description: This is a template for business errors should be returned by
            this API
          schema:
            $ref: '#/definitions/422_MB85'
