swagger: "2.0"
info:
  title: MasterCard Virtual Card Details
  x-ibm-name: mastercard-virtual-card-details
  version: 1.0.3
  description: This API allows user to view virtual card details
host: $(catalog.host)
schemes:
- https
basePath: /
produces:
- application/json
consumes:
- application/json
security:
- oauthconsumer:
  - consumer
- oauthmerchant:
  - merchant
- oauthuser:
  - user
- oauth-consumer:
  - consumer
securityDefinitions:
  oauth-consumer:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider-consumer
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider-consumer/oauth2/token
    scopes:
      consumer: ""
  oauthuser:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: oauth-provider
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider/oauth2/token
    scopes:
      user: Default Scope
  oauthconsumer:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider/oauth2/token
    scopes:
      consumer: ""
  oauthmerchant:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider/oauth2/token
    scopes:
      merchant: ""
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: false
  assembly:
    execute:
    - gatewayscript:
        version: 2.0.0
        title: gatewayscript
        source: context.message.header.set('x-user-metadata',context.get('oauth.verified_access_token.misc_info'));
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(target-url)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
          values: []
        header-control:
          type: blacklist
          values: []
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://secure-card-management-microservice.m11s:3000
      description: The URL of the target service
      encoded: false
  catalogs: {}
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
tags:
- externalDocs:
    description: Find out more on box
    url: http://box.ibm
  name: MasterCard Virtual Card Details
definitions:
  responseCardDetails:
    type: object
    properties:
      cardDetails:
        type: array
        items:
          type: object
          properties:
            cardNumber:
              type: string
              example: 1234-****-****-4567
            expiry:
              type: string
              example: mm/yy
            cvv:
              type: number
              example: 123
paths:
  /rest/api/v1/mastercard/viewCardDetails:
    get:
      tags:
      - Virtual MasterCard Details
      summary: MasterCard Virtual Card Details
      description: ""
      produces:
      - application/json
      parameters:
      - name: X-APP-TYPE
        in: header
        required: true
        description: Describes application or device type.
        type: string
      - name: X-APP-VERSION
        in: header
        required: true
        description: Describes application version 1.0.1.
        type: string
      - name: X-DEVICE-ID
        in: header
        required: true
        description: Describes device ID XDFSD23345435.
        type: string
      - name: X-IP-ADDRESS
        in: header
        required: true
        description: Describes IP Address of the device.
        type: string
      - name: X-CHANNEL
        in: header
        required: true
        description: Describes channel code
        type: string
      - name: X-IBM-CLIENT-ID
        in: header
        required: true
        description: Client credentials required for API Connect
        type: string
      - name: X-MSISDN
        in: header
        required: true
        type: string
      - name: cardPackID
        in: header
        required: true
        type: string
      responses:
        "200":
          description: successful operation
        "401":
          description: Authentication Failed
        "422":
          description: Failed to fetch the pending order.
      consumes: []
