swagger: "2.0"
info:
  title: QR Merchant Notifier APIs
  x-ibm-name: qr-merchant-notifier-apis
  version: 1.0.3
  description: |-
    Contains APIs For QR Merchant Notifiers
    Disabling CORS
host: $(catalog.host)
schemes:
- https
basePath: /
produces:
- application/json
consumes:
- application/json
security:
- oauthmerchant:
  - merchant
- oauthconsumer:
  - consumer
- oauth-consumer:
  - consumer
securityDefinitions:
  oauth-consumer:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider-consumer
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider-consumer/oauth2/token
    scopes:
      consumer: ""
  oauthmerchant:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider/oauth2/token
    scopes:
      merchant: ""
  oauthconsumer:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider/oauth2/token
    scopes:
      consumer: ""
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - gatewayscript:
        version: 2.0.0
        title: gatewayscript
        source: context.message.header.set('x-user-metadata',context.get('oauth.verified_access_token.misc_info'));
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(target-url)$(request.path)
        follow-redirects: false
        timeout: 120
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://account-management-microservice.m11s:3000
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
  catalogs: {}
  cors:
    enabled: false
tags:
- externalDocs:
    description: Find out more on box
    url: http://box.ibm
  name: QR Merchant Ratings APIs
definitions:
  request:
    type: object
    properties:
      msisdn:
        type: string
        example: 923218100301
      name:
        type: string
        example: faisal
      additionalDetails:
        type: object
        properties:
          key:
            type: string
            example: abc
          value:
            type: string
            example: def
    required:
    - msisdn
    - name
  response:
    type: object
    properties:
      mobileNumber1:
        type: object
        properties:
          msisdn:
            type: string
            example: 923218100301
          name:
            type: string
            example: faisal
      mobileNumber2:
        type: object
        properties:
          msisdn:
            type: string
            example: 923218100302
          name:
            type: string
            example: faisal2
  additionalObject:
    type: object
    properties:
      key:
        type: string
        example: abc
      value:
        type: string
        example: def
paths:
  /rest/api/v1/account/qrcode/notifiers:
    put:
      tags:
      - Add/Remove New QR Notifier for a Merchant
      summary: Add/Remove New QR Notifier for a Merchant
      description: ""
      produces:
      - application/json
      parameters:
      - in: query
        name: index
        type: string
      - in: header
        name: X-APP-TYPE
        required: true
        type: string
        enum:
        - Andriod
        - IOS
        - Web
        description: Describes application or device type.
      - in: header
        name: X-APP-VERSION
        required: true
        type: string
        description: Describes application version 1.0.1.
      - in: header
        name: X-DEVICE-ID
        required: true
        type: string
        description: Describes device ID XDFSD23345435.
      - in: header
        name: X-IP-ADDRESS
        required: true
        type: string
        description: Describes IP Address of the device.
      - in: header
        name: X-CHANNEL
        required: true
        type: string
        enum:
        - Third Party
        - Mobile APP
        - Backend Portal
        description: Describes channel code
      - in: header
        name: X-MSISDN
        required: true
        type: string
      - in: body
        name: body
        schema:
          $ref: '#/definitions/request'
        description: The request body for the operation
      responses:
        "200":
          description: successful operation
          schema:
            properties:
              success:
                type: boolean
                example: true
              responseCode:
                type: string
                example: QR-QRN-T04
              responseMessage_en:
                type: string
                example: Successfully Updated Notifiers
              responseMessage_ur:
                type: string
                example: Successfully Updated Notifiers
              data:
                $ref: '#/definitions/response'
              additionalDetails:
                items:
                  $ref: '#/definitions/additionalObject'
        "422":
          description: Error
          schema:
            properties:
              success:
                type: boolean
                example: false
              responseCode:
                type: string
                example: QR-QRN-T05
              responseMessage:
                type: string
                example: Unable to Update Notifiers
    get:
      tags:
      - GET QR Notifiers for a Merchant
      summary: GET QR Notifiers for Merchant
      description: ""
      produces:
      - application/json
      parameters:
      - in: header
        name: X-APP-TYPE
        required: true
        type: string
        enum:
        - Andriod
        - IOS
        - Web
        description: Describes application or device type.
      - in: header
        name: X-APP-VERSION
        required: true
        type: string
        description: Describes application version 1.0.1.
      - in: header
        name: X-DEVICE-ID
        required: true
        type: string
        description: Describes device ID XDFSD23345435.
      - in: header
        name: X-IP-ADDRESS
        required: true
        type: string
        description: Describes IP Address of the device.
      - in: header
        name: X-CHANNEL
        required: true
        type: string
        enum:
        - Third Party
        - Mobile APP
        - Backend Portal
        description: Describes channel code
      - in: header
        name: X-MSISDN
        required: true
        type: string
      responses:
        "200":
          description: successful operation
          schema:
            properties:
              success:
                type: boolean
                example: true
              responseCode:
                type: string
                example: QR-QRN-T02
              responseMessage_en:
                type: string
                example: Successfully Fetched Notifiers
              responseMessage_ur:
                type: string
                example: Successfully Fetched Notifiers
              data:
                $ref: '#/definitions/response'
              additionalDetails:
                items:
                  $ref: '#/definitions/additionalObject'
        "422":
          description: Error
          schema:
            properties:
              success:
                type: boolean
                example: false
              responseCode:
                type: string
                example: QR-QRN-T03
              responseMessage:
                type: string
                example: Unable to Fetch Notifiers
