swagger: "2.0"
info:
  title: QR Payment Static / Dynamic / Till Number
  x-ibm-name: qr-payment-static-dynamic-till-number
  version: 1.0.4
  description: |-
    Contains APIs For QR Payments
    Disabling CORS
host: $(catalog.host)
schemes:
- https
basePath: /
produces:
- application/json
consumes:
- application/json
security:
- oauthmerchant:
  - merchant
- oauthconsumer:
  - consumer
- oauth-consumer:
  - consumer
securityDefinitions:
  oauth-consumer:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider-consumer
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider-consumer/oauth2/token
    scopes:
      consumer: ""
  oauthconsumer:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider/oauth2/token
    scopes:
      consumer: ""
  oauthmerchant:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider/oauth2/token
    scopes:
      merchant: ""
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - gatewayscript:
        version: 2.0.0
        title: gatewayscript
        source: context.message.header.set('x-user-metadata',context.get('oauth.verified_access_token.misc_info'));
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(target-url)$(request.path)
        follow-redirects: false
        timeout: 120
        parameter-control:
          type: blacklist
        header-control:
          type: blacklist
          values:
          - ^X-IBM-Client-Id$
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://payment-and-transaction-microservice.m11s:3000
      description: The URL of the target service
      encoded: false
  catalogs: {}
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  cors:
    enabled: true
tags:
- externalDocs:
    description: Find out more on box
    url: http://box.ibm
  name: QR Payment Static / Dynamic / Till Number
definitions:
  MerchantDetailsRequest:
    type: object
    properties:
      type:
        type: string
        example: qrStatic / qrDynamic / tillNumber
      payload:
        type: string
        example: "00001111"
      remarks:
        type: string
        example: sample remarks
      additionalDetails:
        type: object
        properties:
          key:
            type: string
            example: abc
          value:
            type: string
            example: def
    required:
    - type
    - payload
  MerchantDetailsResponse:
    type: object
    properties:
      merchantMsisdn:
        type: string
        example: 3015091700
      merchantName:
        type: string
        example: Al Barkat
      tillNumber:
        type: string
        example: "00001111"
      merchantRating:
        type: string
        example: "4"
  InitRequest:
    type: object
    properties:
      amount:
        type: number
        example: 500
      identifier:
        type: string
        example: "923015091633"
      identifierType:
        type: string
        example: "1"
      remarks:
        type: string
        example: sample remarks
      additionalDetails:
        type: object
        properties:
          key:
            type: string
            example: abc
          value:
            type: string
            example: def
    required:
    - amount
    - identifier
    - identifierType
  InitResponse:
    type: object
    properties:
      originatorConversationID:
        type: string
        example: AG_20130129T102103
      conversationID:
        type: string
        example: AG_20130129T102103
      transactionID:
        type: string
        example: XD2013012923789234
      txEndDate:
        type: string
        example: 2004-01-05T00:00:00.000Z
      txEndTime:
        type: string
        example: "03:33:12.943"
      amount:
        type: string
        example: "10.00"
      fee:
        type: string
        example: "0.00"
  ConfirmRequest:
    type: object
    properties:
      transactionID:
        type: string
        example: 10710822000
      transactionType:
        type: string
        example: Closed Loop
      paidVia:
        type: string
        example: Scan from Camera, Scan from gallery, Till Number
      qrCode:
        type: string
        example: Static / Till Number
      merchantDetails:
        type: object
        properties:
          msisdn:
            type: string
            example: "923462104357"
          name:
            type: string
            example: Al Barkat.com
          tillNumber:
            type: string
            example: "00000016"
      remarks:
        type: string
        example: sample remarks
      additionalDetails:
        type: object
        properties:
          key:
            type: string
            example: abc
          value:
            type: string
            example: def
    required:
    - transactionID
    - transactionType
    - paidVia
    - qrCode
    - merchantDetails
  ConfirmResponse:
    type: object
    properties:
      txID:
        type: string
        example: 10710822000
      txType:
        type: string
        example: Closed Loop
      paidVia:
        type: string
        example: Scan from Camera, Scan from gallery, Till Number
      qrCode:
        type: string
        example: Static / Till Number
      msisdn:
        type: string
        example: 03xxxxx
      amount:
        type: string
        example: "100"
      fee:
        type: string
        example: "0.00"
      txEndDate:
        type: string
        example: "20140102"
      txEndTime:
        type: string
        example: "210159"
      contextData:
        type: object
        properties:
          ocvID:
            type: string
            example: S_X2013012921001
          cvID:
            type: string
            example: AG_20130129T102103
          merchantDetails:
            type: object
            properties:
              msisdn:
                type: string
                example: "923462104357"
              name:
                type: string
                example: Al Barkat.com
              tillNumber:
                type: string
                example: "00000016"
  additionalObject:
    type: object
    properties:
      key:
        type: string
        example: abc
      value:
        type: string
        example: def
paths:
  /rest/api/v1/payment/qrpayment/merchantdetails:
    post:
      security:
      - Bearer: []
      tags:
      - Fetch Merchant Details
      summary: Fetch Merchant Details
      description: ""
      produces:
      - application/json
      parameters:
      - in: header
        name: X-APP-TYPE
        required: true
        type: string
        enum:
        - Andriod
        - IOS
        - Web
        description: Describes application or device type.
      - in: header
        name: X-APP-VERSION
        required: true
        type: string
        description: Describes application version 1.0.1.
      - in: header
        name: X-DEVICE-ID
        required: true
        type: string
        description: Describes device ID XDFSD23345435.
      - in: header
        name: X-IP-ADDRESS
        required: true
        type: string
        description: Describes IP Address of the device.
      - in: header
        name: X-CHANNEL
        required: true
        type: string
        enum:
        - Third Party
        - Mobile APP
        - Backend Portal
        description: Describes channel code
      - in: header
        name: X-MSISDN
        required: true
        type: string
      responses:
        "200":
          description: successful operation
          schema:
            properties:
              success:
                type: boolean
                example: true
              responseCode:
                type: string
                example: QR-MD-AKSA-T04
              responseMessage_en:
                type: string
                example: Successfully Fetched Details from AKSA
              responseMessage_ur:
                type: string
                example: Successfully Fetched Details from AKSA
              data:
                $ref: '#/definitions/MerchantDetailsResponse'
              additionalDetails:
                items:
                  $ref: '#/definitions/additionalObject'
        "422":
          description: Error
          schema:
            properties:
              success:
                type: boolean
                example: false
              responseCode:
                type: string
                example: QR-MD-AKSA-T02
              responseMessage:
                type: string
                example: Error on AKSA
    parameters:
    - name: body
      in: body
      schema:
        $ref: '#/definitions/MerchantDetailsRequest'
      description: The request body for the operation
  /rest/api/v1/payment/qrpayment/init:
    post:
      security:
      - Bearer: []
      tags:
      - Initiate Customer to Merchant Payment
      summary: Initiate Customer to Merchant Payment
      description: ""
      produces:
      - application/json
      parameters:
      - in: header
        name: X-APP-TYPE
        required: true
        type: string
        enum:
        - Andriod
        - IOS
        - Web
        description: Describes application or device type.
      - in: header
        name: X-APP-VERSION
        required: true
        type: string
        description: Describes application version 1.0.1.
      - in: header
        name: X-DEVICE-ID
        required: true
        type: string
        description: Describes device ID XDFSD23345435.
      - in: header
        name: X-IP-ADDRESS
        required: true
        type: string
        description: Describes IP Address of the device.
      - in: header
        name: X-CHANNEL
        required: true
        type: string
        enum:
        - Third Party
        - Mobile APP
        - Backend Portal
        description: Describes channel code
      - in: header
        name: X-MSISDN
        required: true
        type: string
      responses:
        "200":
          description: successful operation
          schema:
            properties:
              success:
                type: boolean
                example: true
              responseCode:
                type: string
                example: QR-PAY-T34
              responseMessage_en:
                type: string
                example: Init Trans Customer to Merchant Successful
              responseMessage_ur:
                type: string
                example: Init Trans Customer to Merchant Successful
              data:
                $ref: '#/definitions/InitResponse'
              additionalDetails:
                items:
                  $ref: '#/definitions/additionalObject'
        "422":
          description: Error
          schema:
            properties:
              success:
                type: boolean
                example: false
              responseCode:
                type: string
                example: QR-PAY-T02
              responseMessage:
                type: string
                example: Error
    parameters:
    - name: body
      in: body
      schema:
        $ref: '#/definitions/InitRequest'
      description: The request body for the operation
  /rest/api/v1/payment/qrpayment/confirm:
    post:
      security:
      - Bearer: []
      tags:
      - Confirm Customer to Merchant Payment
      summary: Confirm Customer to Merchant Payment
      description: ""
      produces:
      - application/json
      parameters:
      - in: header
        name: X-APP-TYPE
        required: true
        type: string
        enum:
        - Andriod
        - IOS
        - Web
        description: Describes application or device type.
      - in: header
        name: X-APP-VERSION
        required: true
        type: string
        description: Describes application version 1.0.1.
      - in: header
        name: X-DEVICE-ID
        required: true
        type: string
        description: Describes device ID XDFSD23345435.
      - in: header
        name: X-IP-ADDRESS
        required: true
        type: string
        description: Describes IP Address of the device.
      - in: header
        name: X-MPIN
        required: true
        type: string
        description: User MPIN
      - in: header
        name: X-CHANNEL
        required: true
        type: string
        enum:
        - Third Party
        - Mobile APP
        - Backend Portal
        description: Describes channel code
      - in: header
        name: X-MSISDN
        required: true
        type: string
      responses:
        "200":
          description: successful operation
          schema:
            properties:
              success:
                type: boolean
                example: true
              responseCode:
                type: string
                example: QR-PAY-T35
              responseMessage_en:
                type: string
                example: Payment Successful
              responseMessage_ur:
                type: string
                example: Payment Successful
              data:
                $ref: '#/definitions/ConfirmResponse'
              additionalDetails:
                items:
                  $ref: '#/definitions/additionalObject'
        "422":
          description: Error
          schema:
            properties:
              success:
                type: boolean
                example: false
              responseCode:
                type: string
                example: QR-PAY-T02
              responseMessage:
                type: string
                example: Error
    parameters:
    - name: body
      in: body
      schema:
        $ref: '#/definitions/ConfirmRequest'
      description: The request body for the operation
