swagger: "2.0"
info:
  title: QR Transaction History API
  x-ibm-name: qr-transaction-history-api
  version: 1.0.3
  description: |-
    Contains APIs For QR Transaction History
    Disabling CORS
host: $(catalog.host)
schemes:
- https
basePath: /
produces:
- application/json
consumes:
- application/json
security:
- oauthmerchant:
  - merchant
- oauthconsumer:
  - consumer
- oauth-consumer:
  - consumer
securityDefinitions:
  oauth-consumer:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider-consumer
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider-consumer/oauth2/token
    scopes:
      consumer: ""
  oauthmerchant:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider/oauth2/token
    scopes:
      merchant: ""
  oauthconsumer:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider/oauth2/token
    scopes:
      consumer: Default Scope
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - gatewayscript:
        version: 2.0.0
        title: gatewayscript
        source: context.message.header.set('x-user-metadata',context.get('oauth.verified_access_token.misc_info'));
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(target-url)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
          values: []
        header-control:
          type: blacklist
          values: []
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://payment-and-transaction-microservice.m11s:3000
      description: The URL of the target service
      encoded: false
  catalogs: {}
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  cors:
    enabled: true
tags:
- externalDocs:
    description: Find out more on box
    url: http://box.ibm
  name: QR Merchant Ratings APIs
definitions:
  response:
    type: object
    properties:
      txType:
        type: string
        example: Closed Loop
      paidVia:
        type: string
        example: QR
      msisdn:
        type: string
        example: 923046664576
      amount:
        type: string
        example: 923046664576
      contextData:
        type: object
        properties:
          merchantDetails:
            type: object
            properties:
              name:
                type: string
                example: Al Barkat.com
              msisdn:
                type: string
                example: 923046664576
              tillNumber:
                type: string
                example: 14
  additionalObject:
    type: object
    properties:
      key:
        type: string
        example: abc
      value:
        type: string
        example: def
paths:
  /rest/api/v1/payment/qrpayment/history:
    get:
      tags:
      - GET QR Transaction History
      summary: GET QR Transaction History
      description: ""
      produces:
      - application/json
      parameters:
      - in: query
        name: start
        type: string
      - in: query
        name: end
        type: string
      - in: query
        name: range
        type: string
      - in: header
        name: X-APP-TYPE
        required: true
        type: string
        enum:
        - Andriod
        - IOS
        - Web
        description: Describes application or device type.
      - in: header
        name: X-APP-VERSION
        required: true
        type: string
        description: Describes application version 1.0.1.
      - in: header
        name: X-DEVICE-ID
        required: true
        type: string
        description: Describes device ID XDFSD23345435.
      - in: header
        name: X-IP-ADDRESS
        required: true
        type: string
        description: Describes IP Address of the device.
      - in: header
        name: X-CHANNEL
        required: true
        type: string
        enum:
        - Third Party
        - Mobile APP
        - Backend Portal
        description: Describes channel code
      - in: header
        name: X-MSISDN
        required: true
        type: string
      responses:
        "200":
          description: successful operation
          schema:
            properties:
              success:
                type: boolean
                example: true
              responseCode:
                type: string
                example: QR-PH-T02
              responseMessage_en:
                type: string
                example: Successfully Fetched QR Payment History
              responseMessage_ur:
                type: string
                example: Successfully Fetched QR Payment History
              data:
                $ref: '#/definitions/response'
              additionalDetails:
                items:
                  $ref: '#/definitions/additionalObject'
        "422":
          description: Error
          schema:
            properties:
              success:
                type: boolean
                example: false
              responseCode:
                type: string
                example: QR-PH-T03
              responseMessage:
                type: string
                example: Unable to Fetch QR Payment History
