swagger: "2.0"
info:
  title: Request to pay Bulk Reject
  x-ibm-name: request-to-pay-bulk-reject
  version: 1.0.4
  description: |-
    Request to pay Bulk Reject
    Disabling CORS
host: $(catalog.host)
schemes:
- https
basePath: /
produces:
- application/json
consumes:
- application/json
security:
- oauthmerchant:
  - merchant
- oauthconsumer:
  - consumer
- oauth-consumer:
  - consumer
securityDefinitions:
  oauth-consumer:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider-consumer
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider-consumer/oauth2/token
    scopes:
      consumer: ""
  oauthmerchant:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider/oauth2/token
    scopes:
      merchant: ""
  oauthconsumer:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: oauth-provider
    tokenUrl: https://$(catalog.url)/rest/api/oauth-provider/oauth2/token
    scopes:
      consumer: ""
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - gatewayscript:
        version: 2.0.0
        title: gatewayscript
        source: context.message.header.set('x-user-metadata',context.get('oauth.verified_access_token.misc_info'));
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(target-url)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
          values: []
        header-control:
          type: blacklist
          values: []
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://payment-and-transaction-microservice.m11s:3000
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
  catalogs: {}
  cors:
    enabled: false
definitions:
  genericSuccessResponse:
    type: object
    properties:
      success:
        type: boolean
        example: true
      responseCode:
        type: string
        example: PT-RTP-T04
      message_en:
        type: string
        example: Request successful
      message_ur:
        type: string
        example: درخواست کامیاب
  error400:
    description: Bad Request
    type: object
    title: Bad Request
    properties:
      success:
        type: string
        example: "false"
      responseCode:
        type: string
        example: PT-RTP-T01
      responseMessage:
        type: string
        example: Bad Request
  error401:
    type: object
    title: Unauthorized
    properties:
      success:
        type: string
        example: "false"
      responseCode:
        type: string
        example: T02
      responseMessage:
        type: string
        example: Authentication Failed
  error402:
    type: object
    title: Timed-ou or Failed to submit the transaction to CPS
    properties:
      success:
        type: string
        example: "false"
      responseCode:
        type: string
        example: T03
      responseMessage:
        type: string
        example: ""
  error409:
    type: object
    title: Conflict
    properties:
      success:
        type: string
        example: "false"
      responseCode:
        type: string
        example: T06
      responseMessage:
        type: string
        example: Conflict
  error500:
    type: object
    title: Server Error
    properties:
      success:
        type: string
        example: "false"
      responseCode:
        type: string
        example: T07
      responseMessage:
        type: string
        example: Internal Server Error
  rejectRequest:
    type: object
    properties:
      invoiceID:
        type: string
        example: 1123abc
      invoiceType:
        type: string
        example: requestInvoice | quickPay
        enum:
        - requestInvoice
        - quickPay
  additionalObject:
    type: object
    properties:
      key:
        type: string
        example: abc
      value:
        type: string
        example: def
paths:
  /rest/api/v1/requesttopay/reject:
    post:
      security:
      - Bearer: []
      tags:
      - Request To Pay
      summary: Request to pay via quickpay
      description: ""
      produces:
      - application/json
      parameters:
      - in: header
        name: X-APP-TYPE
        required: true
        type: string
        enum:
        - Andriod
        - IOS
        - Web
        description: Describes application or device type.
      - in: header
        name: X-APP-VERSION
        required: true
        type: string
        description: Describes application version 1.0.1.
      - in: header
        name: X-DEVICE-ID
        required: true
        type: string
        description: Describes device ID XDFSD23345435.
      - in: header
        name: X-IP-ADDRESS
        required: true
        type: string
        description: Describes IP Address of the device.
      - in: header
        name: X-MPIN
        required: true
        type: string
        description: User MPIN
      - in: header
        name: X-CHANNEL
        required: true
        type: string
        enum:
        - Third Party
        - Mobile APP
        - Backend Portal
        description: Describes channel code
      - in: header
        name: X-MSISDN
        required: true
        type: string
      - in: body
        name: body
        required: true
        schema:
          items:
            $ref: '#/definitions/rejectRequest'
        description: The request body for the operation
      responses:
        "200":
          description: successful operation
          schema:
            properties:
              success:
                type: boolean
                example: true
              successCode:
                type: number
                example: PT-RTP-T04
              message_en:
                type: string
                example: Request sent Successfully
              message_ur:
                type: string
                example: Request sent Successfully
        "422":
          description: Error
          schema:
            properties:
              success:
                type: boolean
                example: false
              successCode:
                type: number
                example: PT-RTP-T01
              message_en:
                type: string
                example: Request sent Successfully
              message_ur:
                type: string
                example: Request sent Successfully
